App/urls.py
"""
URL configuration file for the application.

This file defines the main URLs for the application, including
views for the home page, contact form, authentication,
blog, portfolio, and tutorials.

"""

from django.contrib import admin
from django.urls import path

from core import views as c

from authentication import views as auth
from portfolio import views as portfolio

from blog.views import ArticleListView, ArticleByThemeDetailView
from tutorial.views import TutorialListView, TutorialDetailView


urlpatterns = [
    path("personnal_url_for_admin_dashboard/", admin.site.urls),
    path("", c.index, name="home"),
    path("contactez-moi", c.contact, name="contact"),
    # authentication
    path("login", auth.log_in, name="connexion"),
    path("logout", auth.log_out, name="deconnexion"),
    path("profile", auth.profile, name="profile"),
    path("profile/update", auth.update, name="profile_update"),
    # blog
    path("oodysee-dev", ArticleListView.as_view(), name="articles"),
    path("oodysee-dev/<slug:slug>", ArticleByThemeDetailView.as_view(), name="theme"),
    # portfolio
    path("portfolio", portfolio.achievement, name="portfolio"),
    # tutorial
    path("astuces", TutorialListView.as_view(), name="tutos"),
    path("astuces/<slug:slug>", TutorialDetailView.as_view(), name="tuto-theme"),
    # path("", , name=""),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse


class Theme(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    describe = models.CharField(max_length=500, null=True, blank=True)
    order = models.IntegerField(default=0)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("theme_detail", kwargs={"slug": self.slug})


class Tag(models.Model):
    tag_name = models.CharField(max_length=100)

    class Meta:
        ordering = ["tag_name"]

    def __str__(self):
        return f"{self.tag_name}"


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)
    subtitle = models.CharField(max_length=500, null=True, blank=True)
    text = RichTextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="blog", null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, editable=False)
    order = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    tags = models.ManyToManyField(Tag, blank=True, related_name="articles")

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"slug": self.slug})

tutorial/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from ckeditor.fields import RichTextField
from django.urls import reverse
from django_resized import ResizedImageField


class Theme(models.Model):
    title = models.CharField(max_length=100)
    describe = models.CharField(max_length=500, null=True, blank=True)
    active = models.BooleanField(default=True)
    slug = models.SlugField(max_length=100)
    img = ResizedImageField(
        size=[300, 300],
        crop=["middle", "center"],
        upload_to="tutorial",
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return f"{self.title}"


class Tag(models.Model):
    tag_name = models.CharField(max_length=100)

    class Meta:
        ordering = ["tag_name"]

    def __str__(self):
        return f"{self.tag_name}"

    def get_absolute_url(self):
        return reverse("tag", kwargs={"slug": self.slug})


class Tutorial(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    theme = models.ForeignKey(Theme, on_delete=models.SET_NULL, null=True)
    subtitle = models.CharField(max_length=500, null=True, blank=True)
    text = RichTextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    order = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    date_create = models.DateTimeField(auto_now_add=True, editable=False)
    date_update = models.DateTimeField(auto_now=True, editable=True)
    tags = models.ManyToManyField(Tag, blank=True, related_name="tutos")

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return f"{self.theme} : {self.title} "

    def save(self, *args, **kwargs) -> None:
        self.text = mark_safe(self.text)
        super(Tutorial, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("tutorial_detail", kwargs={"slug": self.slug})

templates/mailbox/contact_form.html
{% extends 'ookamy_base.html'%}
{% load static %}

{% block style %}{% endblock %}
{% block title %}Contactez-moi{% endblock %}
{% block h1 %}{% endblock %}
{% block content %}
<!-- contenu -->
<div class="grid-x grid-margin-x  align-center">

    <div class="cell  small-12 medium-10 card ">
        <div class="cell text-center">
            <img src="{% static 'img/ooka.svg' %}" style="width: 185px;" alt="logo">
            <h6 class="ooka-title" style="text-align: center !important;" >Me contacter</h6>
        </div>
        <div class="cell">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-outline">
                    <label class="form-label" for="{{form.name.id_for_label}}">Nom :</label>
                    <input type="text" required id="{{form.name.id_for_label}}" name="name" class="form-control"
                        placeholder="Nom" />
                </div>
                <div class="form-outline">
                    <label class="form-label" for="id_template" >Select Menu
                        <select name="template" id="id_template">
                          <option class="form-control" value="basic">basic</option>
                          <option class="form-control" value="contact">contact</option>
                          <option class="form-control" value="contact_info">contact_info</option>
                          <option class="form-control" value="welcome">welcome </option>
                          <option class="form-control" value="newsletter">newsletter</option>
                        </select>
                      </label>
                </div>

                <div class="form-outline">
                    <label class="form-label" for="{{form.email.id_for_label}}">Email : Veuillez donner une adresse
                        valide pour être sûre d'avoir une réponse =)</label>
                    <input type="email" id="{{form.email.id_for_label}}" name="email" required class="form-control"
                        placeholder="Email" />
                </div>

                <div class="form-outline">
                    <label class="form-label" for="{{form.message.id_for_label}}">Message :</label>
                    <textarea class="form-control" id="{{form.message.id_for_label}}" rows="4" name="message"
                        maxlength="1000" required></textarea>
                    <div class="text-right"><span id="current-caracter">0</span>/1000</div>
                </div>

                <div class="text-center">
                    <button class="button super-btn submit" type="submit">Envoyer</button>
                </div>
            </form>
        </div>


    </div>
</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function () {
        let currentCaract = $('#current-caracter');
        let textArea = $('#{{form.message.id_for_label}}');

        textArea.on("input", function () {
            var maxlength = $(this).attr("maxlength");
            var currentLength = $(this).val().length;

            //console.log(maxlength - currentLength + "/" + maxlength);
            currentCaract.html(currentLength);
        });
    }); 
</script>
{% endblock %}

templates/mailbox/newsletter_dashboard.html
{% extends 'ookamy_base.html'%}
{% load static %}

{% block style %}{% endblock %}
{% block title %}Gestion des Newsletters{% endblock %}
{% block h1 %}{% endblock %}
{% block content %}{% block content %
<!-- contenu -->
<div class="grid-x grid-margin-x  align-center">
<a class="hollow button success" href="{% url 'news-add' %}"><i class="fa-regular fa-square-plus"></i> Créer une News</a>

<!-- tableau pour visualiser / envoyer les newsletter -->
<table class="hover">
    {% csrf_token %}
    <thead>
        <tr>
          <th class="text-center">date creation</th>
          <th class="text-center">sujet</th>
          <th class="text-center">body</th>
          <th class="text-center">Articles associer</th>
          <th class="text-center">Tuto's associer</th>
          <th class="text-center">envoyer</th>
        </tr>
    </thead>  
    <tbody>
        {% for n in news %}
        <tr>
            <td class="text-center">{{n.date_create}}</td>
            <td class="text-center">{{n.subject}}</td>
            <td class="text-center">
                <p>
                    <button class="button secondary" data-open="article-{{n.pk}}xx"><i class="fa-regular fa-eye"></i></button></p>
                <div class="large reveal" id="article-{{n.pk}}xx" data-reveal>
                    <button class="close-button" data-close aria-label="Close Accessible Modal" type="button">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <a class="secondary button clear" href="{% url 'template' n.pk %}"><span title="Voir le resultat"><i class="fa-regular fa-eye"></i></span></a>
                    {{n.body|safe}}
                </div>
            </td>
            <td>
                {% if n.article_list.all %}
                <ul>
                {% for article in n.article_list.all %}
                        <li>{{article.title}}</li>
                {% endfor %}
                </ul>
                {% endif %}
            </td>
            <td>
                {% if n.tutorial_list.all %}
                <ul>
                {% for tutorial in n.tutorial_list.all %}
                        <li>{{tutorial.title}}</li>
                {% endfor %}
                </ul>
                {% endif %}
            </td>
            <td >
                {% if n.send %}
                <div class="text-center" style="color: green;">
                    <span class="align-center" title="{{n.date_send}}">
                        <i class="fa-solid fa-check"></i><br>
                        {{n.date_send}}
                    </span>
                </div>
                
                
                {% else %}
                <div class="tiny button-group align-center ">
                    <a class="warning button hollow"><span title="envoyer" onclick="send_newsletter('{{n.pk}}');"><i class="fa-solid fa-share"></i></span></a>
                    <a class="primary button hollow" href="{% url 'newsletter_form_update' n.pk %}" ><span title="Editer"><i class="fa-solid fa-pen-fancy"></i></span></a>
                    <a class="alert button hollow"><span title="supprimer" onclick="d_newsletter('{{n.pk}}');"><i class="fa-regular fa-trash-can"></i></span></a>
                </div>
                {% endif %}
            
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<hr>
<div>
    {{emails}}
</div>
</div>
{% endblock %}
{% block script %}
<script>
    function send_newsletter(data){
        let formData = new FormData();
        formData.append('id', data);

        let csrfTokenValue = document.querySelector('[name=csrfmiddlewaretoken]').value;
        // console.log(csrfTokenValue)
        const request = new Request('{% url "news-send" %}', {
            method: 'POST',
            body: formData,
            headers: {'X-CSRFToken': csrfTokenValue}  // On ajoute le token dans l'en-tête
        });
        fetch(request)
            .then(response => response.json())
            .then(result => {
                // console.log(result['result'])
                if ( result['result'] == 'OK'){
                    location.reload();
                }
            })
    };

    function d_newsletter(data){
        let formData = new FormData();
        formData.append('id', data);

        let csrfTokenValue = document.querySelector('[name=csrfmiddlewaretoken]').value;
        // console.log(csrfTokenValue)
        const request = new Request('{% url "news-delete" %}', {
            method: 'POST',
            body: formData,
            headers: {'X-CSRFToken': csrfTokenValue}  // On ajoute le token dans l'en-tête
        });
        fetch(request)
            .then(response => response.json())
            .then(result => {
                if ( result['result'] == 'OK'){
                    location.reload();
                }
            })
    };

</script>


{% endblock %}

templates/mailbox/newsletter_form.html
{% extends 'ookamy_base.html'%}
{% load static %}

{% block style %}{% endblock %}
{% block title %}Contactez-moi{% endblock %}
{% block h1 %}{% endblock %}
{% block content %}
<!-- contenu -->
<div class="grid-x grid-margin-x  align-center">

    <div class="cell  small-12 medium-10 card ">
        <div class="cell text-center">
            <img src="{% static 'img/ooka.svg' %}" style="width: 185px;" alt="logo">
            <h6 class="ooka-title" style="text-align: center !important;" >Campagne de Newsletter</h6>
        </div>
        <div class="cell">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-outline">
                    <label class="form-label" for="{{form.subject.id_for_label}}">Objet de la newsletter : </label>
                    {{form.subject}}
                </div>
                <div class="form-outline">
                    <label class="form-label" for="{{form.body.id_for_label}}">Message :</label>
                    {{form.media}}
                    {{form.body}}
                </div>
                <div class="grid-x grid-padding-x" >
                    <div class="medium-6 cell">
                        <label for="{{form.article_list.id_for_label}}">Liste des articles mis en avant :</label>
                        {{form.article_list}}
                    </div>
                    <div class="medium-6 cell">
                        <label for="{{form.tutorial_list.id_for_label}}">Liste des Tutoriels mis en avant :</label>
                        {{form.tutorial_list}}
                    </div>
                </div>
                <div class="text-center">
                    <button class="button super-btn submit" type="submit">Envoyer</button>
                </div>
            </form>
        </div>


    </div>
</div>
{% endblock %}
{% block script %}
{% endblock %}

templates/mailbox/newsletterlist_form.html
{% extends '../ookamy_base.html'%}
{% load static %}

{% block title %}{% endblock %}

{% block h1 %}{% endblock %}
{% block content %}

<div class="grid-x grid-margin-x align-center">
    {% for m in mail %}
        {{m}}
    {% endfor %}
</div>
{% endblock %}
{% block script %}

{% endblock %}