App/urls.py
"""
URL configuration file for the application.

This file defines the main URLs for the application, including
views for the home page, contact form, authentication,
blog, portfolio, and tutorials.

"""

from django.contrib import admin
from django.urls import path

from core import views as c

from authentication import views as auth
from portfolio import views as portfolio

from blog.views import ArticleListView, ArticleByThemeDetailView
from tutorial.views import TutorialListView, TutorialDetailView


urlpatterns = [
    path("personnal_url_for_admin_dashboard/", admin.site.urls),
    path("", c.index, name="home"),
    path("contactez-moi", c.contact, name="contact"),
    # authentication
    path("login", auth.log_in, name="connexion"),
    path("logout", auth.log_out, name="deconnexion"),
    path("profile", auth.profile, name="profile"),
    path("profile/update", auth.update, name="profile_update"),
    # blog
    path("oodysee-dev", ArticleListView.as_view(), name="articles"),
    path("oodysee-dev/<slug:slug>", ArticleByThemeDetailView.as_view(), name="theme"),
    # portfolio
    path("portfolio", portfolio.achievement, name="portfolio"),
    # tutorial
    path("astuces", TutorialListView.as_view(), name="tutos"),
    path("astuces/<slug:slug>", TutorialDetailView.as_view(), name="tuto-theme"),
    # path("", , name=""),
]

tutorial/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from ckeditor.fields import RichTextField
from django.urls import reverse
from django_resized import ResizedImageField


class Theme(models.Model):
    title = models.CharField(max_length=100)
    describe = models.CharField(max_length=500, null=True, blank=True)
    active = models.BooleanField(default=True)
    slug = models.SlugField(max_length=100)
    img = ResizedImageField(
        size=[300, 300],
        crop=["middle", "center"],
        upload_to="tutorial",
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return f"{self.title}"


class Tag(models.Model):
    tag_name = models.CharField(max_length=100)

    class Meta:
        ordering = ["tag_name"]

    def __str__(self):
        return f"{self.tag_name}"

    def get_absolute_url(self):
        return reverse("tag", kwargs={"slug": self.slug})


class Tutorial(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    theme = models.ForeignKey(Theme, on_delete=models.SET_NULL, null=True)
    subtitle = models.CharField(max_length=500, null=True, blank=True)
    text = RichTextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    order = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    date_create = models.DateTimeField(auto_now_add=True, editable=False)
    date_update = models.DateTimeField(auto_now=True, editable=True)
    tags = models.ManyToManyField(Tag, blank=True, related_name="tutos")

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return f"{self.theme} : {self.title} "

    def save(self, *args, **kwargs) -> None:
        self.text = mark_safe(self.text)
        super(Tutorial, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("tutorial_detail", kwargs={"slug": self.slug})

tutorial/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from tutorial.models import Tutorial, Theme


class TutorialListView(ListView):
    model = Tutorial
    template_name = "tutorial/tutorials.html"
    ordering = ["-date_create"]

    def get_queryset(self):
        return super().get_queryset().filter(theme__active=True)

    def get_context_data(self, **kwargs):
        context = super(TutorialListView, self).get_context_data(**kwargs)
        tutos = Tutorial.objects.all().filter(theme__active=True)
        tuto_list = []
        for tuto in tutos:
            t = {"title": tuto.title, "description": tuto.subtitle, "theme": tuto.theme}
            tuto_list.append(t)
        context["tutorials"] = tuto_list
        return context


class TutorialDetailView(DetailView):
    model = Theme
    template_name = "tutorial/tutorial.html"

    def get_queryset(self):
        return super().get_queryset().filter(active=True)

    def get_context_data(self, **kwargs):
        context = super(TutorialDetailView, self).get_context_data(**kwargs)
        context["object_list"] = Tutorial.objects.all().filter(theme__active=True)
        return context

templates/tutorial/tutorial.html
{% extends 'ookamy_base.html'%}
{% load static %}

{% block style %}{% endblock %}
{% block title %}{{theme.title}}{% endblock %}
{% block h1 %}{% endblock %}
{% block content %}
 <!-- Affiche la liste des theme se base sur blog_theme -->
 <div class="grid-x grid-margin-x align-center">
    {% for a in theme.tutorial_set.all %}
    <section class="card cell small-12 medium-10" id="{{a.slug}}" >
        <h3 class="ooka-title">{{ a.title }}</h3>
        <small class="ooka-subtitle ">Dernière modification: {{a.date_modif|date:'j F Y'}}</small>
        {{ a.text|safe }}
    </section>
    {% endfor %}
</div>
{% endblock %}
{% block script %}{% endblock %}

templates/tutorial/tutorials.html
{% extends 'ookamy_base.html'%}
{% load static %}

{% block style %}
<!-- <style>
    body {
        background: linear-gradient(to right top, #eb9f12, #e38802, #da7000, #d05800, #c43e01, #b82f05, #ab1e08, #9e060a, #8e050a, #7e0509, #6f0508, #600505);
    }
</style> -->
{% endblock %}
{% block title %}Les Chafouineries d'Ookamy{% endblock %}

{% block content %}
<div id="tutorial-module" class="grid-x">
    <div class="cell card">
        <div class="grid-x">
            <div class="cell smal-12 medium-4 ">
                <div class="cell small-12">
                    <h1 class="h1-title">Toutes les astuces</h1>
                </div>
                <div class="cell small-12">
                    <p class="subheader text-justify">
                        Lors de mes diverses expérimentations de développement, 
                        il arrive souvent qu'une épreuve s'offre à moi. <br>
                        La solution est plus timide à se présenter, parfois, elle met quelques heures, jours à éclore. <br>
                        Je partage avec vous ses astuces qui je l'espère seront simple à comprendre et utiles à vos développements.
                        <cite class="txt-right">Ookamy</cite>
                    </p>
                </div>
            </div>

            <div class="cell small-12 medium-4 text-center hide-for-small-only">
                <img class="img-fluid" src="{% static 'img/tutorial/idea.png' %}"
                    alt="Representation d'une idée ingénieuse" height="200px" width="200px">
            </div>

            <div class="cell small-12 medium-4 text-center flex-container flex-dir-column">
                <div class="cell grid-x flex-child-grow ">
                    {% if object_list %}
                    {% regroup object_list|dictsort:"theme.title" by theme as t_list %}
                    {% for theme, articles in t_list %}
                        <div class="cell small-3 text-center">
                            <a href="{% url 'tuto-theme' theme.slug %}">
                                {{theme|capfirst}}
                            </a>
                        </div>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="cell small-12 flex-child-shrink">
                    <input id="search-field" type="text" placeholder="Cherche une Chafouinerie">
                </div>
            </div>
        </div>
    </div>
</div>

<div id="tutorial-module" class="grid-x grid-margin-x align-center">
    {% for a in object_list %}

    <section class="tuto-card card cell small-12 medium-6 large-4 flex-container flex-dir-column">
        <label class="hidden-label hide"> {{a.theme}}, {{ a.title }}, {{a.subtitle}},{% for t in a.tags.all %} {{t}},{% endfor %} {{ a.slug }}</label>
        <div class="flex-child-auto">
            <h3 class="ooka-title">
                <a class="ooka-theme-title" href="{% url 'tuto-theme' a.theme.slug %}"># {{a.theme}}</a> : {{ a.title }}
            </h3>
            <small class="ooka-subtitle ">{{a.subtitle}}</small>
        </div>
        <div class="flex-child-grow">
            {{ a.text|safe|striptags|truncatechars:300 }}
            <br>
            <a class="" href="{% url 'tuto-theme' a.theme.slug %}#{{ a.slug }}">
                Lire l'article
            </a>
        </div>
        <div class="flex-child-shrink txt-right">
            <cite class="">{% for t in a.tags.all %}#{{t}} {% endfor %}</cite>
            <small class="ooka-date">Dernière modification: {{a.date_modif|date:'j F Y'}}</small>
        </div>
    </section>

    {% endfor %}
</div>
{% endblock %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/fuzzysort@2.0.1/fuzzysort.min.js"></script>
<script>
    // Variable pour le tableau de la recherche
    let tutorials = []; 
    
    let searchOptions = {
        threshold: -1000,  // Pour ne pas retourner les mauvais resultats
        limit: 10, // Nombre de resultat max 
        allowTypo: true, // On autorise une faute de frappe
        key: "label", // Clé du Dico pour la recherche
    };

    /**
    * Optimise une chaine de caractère pour la recherche de menu
    * Mise en minuscule et remplacement des accents courant
    * @param {string} string la chaine de caractère à changer
    * @return {string} la chaine de caractère modifiée
    */
    function replaceForSearch(string) {
        string = string.toLowerCase();
    
        string = string.replace(new RegExp(/[àáâãäå]/g),"a");
        string = string.replace(new RegExp(/æ/g),"ae");
        string = string.replace(new RegExp(/ç/g),"c");
        string = string.replace(new RegExp(/[èéêë]/g),"e");
        string = string.replace(new RegExp(/[ìíîï]/g),"i");
        string = string.replace(new RegExp(/ñ/g),"n");
        string = string.replace(new RegExp(/[òóôõö]/g),"o");
        string = string.replace(new RegExp(/½/g),"oe");
        string = string.replace(new RegExp(/[ùúûü]/g),"u");
        string = string.replace(new RegExp(/[ýÿ]/g),"y");
    
        return string
    };
 
    function searchTutorials(search){

        // /!\ les accents
        let searchNoAccents = replaceForSearch(search);
        if (search){
            // On cache toute les cartes
            $('.tuto-card').hide();
            //console.log(search);
            // on recherche la valeur de la rechercge dans le tableau
            let results = fuzzysort.go(searchNoAccents, tutorials, searchOptions);

            if (results){
                // console.log(results);
                results.forEach( function(resultItem){
                    let labelTutorial = resultItem['obj']['item'];
                    let inputFieldTuto = $(labelTutorial).closest('.tuto-card');
                    // affiche le resultat
                    // console.log(labelTutorial);
                    // console.log(inputFieldTuto);
                    inputFieldTuto.show()
                });
            };
        } else {
            // quand la recherche est effacé / vide
            $('.tuto-card').show();
        };
    };
    
    
    
    $(document).ready(function () {
        // creation du tableau/dico avec tous les tuto
        // hidden-label regroupe => theme, titre, soustitre, tags, slug
        $(".hidden-label").each(function(){
            tutorials.push({
                "label":replaceForSearch($(this).text()),
                "item": $(this)
            });
        });

        // Recherche dans Tutorial
        $("#search-field").on('input', function(){
            searchTutorials($(this).val());
        });
    }); 
</script>
{% endblock %}