App/urls.py
"""
URL configuration file for the application.

This file defines the main URLs for the application, including
views for the home page, contact form, authentication,
blog, portfolio, and tutorials.

"""

from django.contrib import admin
from django.urls import path

from core import views as c

from authentication import views as auth
from portfolio import views as portfolio

from blog.views import ArticleListView, ArticleByThemeDetailView
from tutorial.views import TutorialListView, TutorialDetailView


urlpatterns = [
    path("personnal_url_for_admin_dashboard/", admin.site.urls),
    path("", c.index, name="home"),
    path("contactez-moi", c.contact, name="contact"),
    # authentication
    path("login", auth.log_in, name="connexion"),
    path("logout", auth.log_out, name="deconnexion"),
    path("profile", auth.profile, name="profile"),
    path("profile/update", auth.update, name="profile_update"),
    # blog
    path("oodysee-dev", ArticleListView.as_view(), name="articles"),
    path("oodysee-dev/<slug:slug>", ArticleByThemeDetailView.as_view(), name="theme"),
    # portfolio
    path("portfolio", portfolio.achievement, name="portfolio"),
    # tutorial
    path("astuces", TutorialListView.as_view(), name="tutos"),
    path("astuces/<slug:slug>", TutorialDetailView.as_view(), name="tuto-theme"),
    # path("", , name=""),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse


class Theme(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    describe = models.CharField(max_length=500, null=True, blank=True)
    order = models.IntegerField(default=0)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("theme_detail", kwargs={"slug": self.slug})


class Tag(models.Model):
    tag_name = models.CharField(max_length=100)

    class Meta:
        ordering = ["tag_name"]

    def __str__(self):
        return f"{self.tag_name}"


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)
    subtitle = models.CharField(max_length=500, null=True, blank=True)
    text = RichTextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="blog", null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, editable=False)
    order = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    tags = models.ManyToManyField(Tag, blank=True, related_name="articles")

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"slug": self.slug})

blog/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.contrib import messages


from blog.models import Article, Theme


# Tous les articles
class ArticleListView(ListView):
    paginate_by = 4
    model = Article
    template_name = "blog/blogs.html"

    def get_queryset(self):
        return super().get_queryset().filter(active=True).filter(theme__active=True)

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        # context['object_list'] = Article.objects.all().filter(active=True)
        context["object_list"] = self.get_queryset()
        return context


# Le detail d'un seul article
class ArticleDetailView(DetailView):
    model = Article
    template_name = "blog/blog.html"

    def get_queryset(self):
        return super().get_queryset().filter(active=True).filter(theme__active=True)

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        context["object_list"] = self.get_queryset()
        return context


# Tous les articles d'un seule thème
class ArticleByThemeDetailView(DetailView):
    model = Theme
    template_name = "blog/blog_theme.html"

    def get_queryset(self):
        return super().get_queryset().filter(active=True)

    def get_context_data(self, **kwargs):
        context = super(ArticleByThemeDetailView, self).get_context_data(**kwargs)
        # context['object_list'] = Article.objects.all().filter(active=True).filter(theme__active=True)
        return context

templates/blog/blog.html
{% extends 'ookamy_base.html'%}
{% load static %}

{% block title %}{{article.title}}{% endblock %}

{% block h1 %}{% endblock %}
{% block content %}

<div class="grid-x grid-margin-x align-center">
    <!-- contenu -->
    <div class="cell small-12 medium-10 large-8" id="super-anchor" data-something>
        <div class="card">
            <!-- titre & sous titre -->
            <div class="card-section">
                <h3 class="ooka-title">{{article.title}}</h3>
                <h6 class="ooka-subtitle ">{{article.subtitle}}</h6>
            </div>
            <!-- img & text & author-->

            {% if article.image %}{% for i in article.image.all %}
            <img src="{% static '/media/' %}{{i.img}}" class="box-sh-image blog-img" alt="{{i.title}}" title="{{i.title}}" />
            {% endfor %}{% endif %}

            <div class="card-section bb-tr50">
                {{article.text|safe}}
            </div>

            <div class="card-section mt-10">
                <div class="grid-x align-middle">
                    <div class="cell small-6 text-center">
                        <img src="{% static '/media/' %}{{ article.author.profile.image }}" class="avatar-blog" alt="" />
                    </div>
                    <div class="cell small-6 text-center">
                        <span> Publié le <u>{{article.date}}</u> par</span>
                        <h5 class="">{{article.author|capfirst}}</h5>
                        Categorie : <a href="{% url 'theme' article.theme.slug %}">
                            {{article.theme}}
                        </a></p>
                    </div>
                    <div class="cell small-12">
                        <p class="text-center"><strong>Commentaires: {{article.review_set.all.count }}</strong></p>
                    </div>
                </div>
            </div>

            <div class="card-section">
            {% if request.user.is_authenticated %}
                {% for c in article.review_set.all %}
                <div class="col-10">
                    <p class="mb-2">Par <strong>{{c.reviewer|upper}}</strong>, {{c.date}}</p>
                    <p>{{c.review}}</p>
                    <hr class="mx-5">
                </div>
                {% endfor %}
            {% endif %}
            </div>
            {% if request.user.is_authenticated%}
            <div class="card-section">
                <p class="text-center"><strong>Laisser un commentaire</strong></p>
                <form action="/review/" method="POST">
                    <input type="hidden" name="moderate" value="False">
                    <input type="hidden" name="article" value="{{article.id}}">
                    <input type="hidden" name="reviewer" value="{{request.user}}">
                    {% csrf_token %}
                    <div class="">
                        <label class="form-label" for="review">Commentaire</label>
                        <textarea class="form-control" id="review" rows="4" name="review" maxlength="400"></textarea>
                        <div class="text-right"><span id="current-caracter">0</span>/400</div>
                    </div>
                    <div class="text-center">
                        <button class="button super-btn" type="submit">Envoyer</button>
                    </div>
                </form>
            </div>
            {% endif %}

        </div>
    </div>

</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function () {
        let currentCaract = $('#current-caracter');
        let textArea = $('#review');

        textArea.on("input", function () {
            var maxlength = $(this).attr("maxlength");
            var currentLength = $(this).val().length;

            //console.log(maxlength - currentLength + "/" + maxlength);
            currentCaract.html(currentLength);
        });
    }); 
</script>
{% endblock %}

templates/blog/blog_theme.html
{% extends 'ookamy_base.html'%}
{% load static %}

{% block title %}Le Blog d'Ookamy{% endblock %}
{% block h1 %}{% endblock %}
{% block content %}
<div class="grid-x grid-margin-x align-center">
    <!-- contenu -->
    <div class="cell small-12 medium-10 large-8" id="super-anchor" data-something>
        {% for a in theme.article_set.all %}
        {% if a.active %}
        <div class="card">
            <!-- titre & sous titre -->
            <div class="card-section">
                <h3 class="ooka-title">{{a.title}}</h3>
                <h6 class="ooka-subtitle ">{{a.subtitle}}</h6>
            </div>
            <!-- img & text & author-->

            {% if a.image %}
            <img src="{% static '/media/' %}{{a.image}}" class="box-sh-image blog-img" alt="{{a.title}}" title="{{a.title}}" />
            {% endif %}

            <div class="card-section bb-tr50">
                {{a.text|safe}}
            </div>

            <div class="card-section mt-10">
                <div class="grid-x align-middle">
                    <div class="cell small-2 text-center">
                        <img src="{% static '/media/' %}{{ a.author.profile.image }}" class="avatar-blog" alt="" />
                    </div>
                    <div class="cell small-6 text-center">
                        <span> Publié le <u>{{a.date}}</u> par</span>
                        <h5 class="">{{a.author|capfirst}}</h5>
                        Categorie : <a href="{% url 'theme' a.theme.slug %}">
                            {{a.theme}}
                        </a></p>
                    </div>


                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}

    </div>

</div>

{% endblock %}

templates/blog/blogs.html
{% extends 'ookamy_base.html'%}
{% load static %}
{% load filters %}
{% block style %}{% endblock %}
{% block title %}Blog d'Ookamy{% endblock %}
{% block h1 %}{% endblock %}
{% block content %}
<!-- template blog/tuto -->
<div class="grid-x grid-margin-x align-center">
    <!-- contenu -->
    {% if page_obj %}
    <div class="cell small-12 medium-10 large-8" id="super-anchor" data-something>
        {% for a in page_obj %}
        <div class="card">
            <!-- titre & sous titre -->
            <div class="card-section">
                <h3 class="ooka-title">{{a.title}}</h3>
                <h6 class="ooka-subtitle ">{{a.subtitle}}</h6>
            </div>
            <!-- img & text & author-->

            {% if a.image %}
            <img src="{% static '/media/' %}{{a.image}}" class="box-sh-image blog-img" alt="{{a.title}}" title="{{a.title}}" />
            {% endif %}

            <div class="card-section bb-tr50">
                {{a.text|safe}}
            </div>

            <div class="card-section mt-10">
                <div class="grid-x align-middle">
                    <div class="cell small-2 text-center">
                        <img src="{% static '/media/' %}{{ a.author.profile.image }}" class="avatar-blog" alt="" />
                    </div>
                    <div class="cell small-6 text-center">
                        <span> Publié le <u>{{a.date}}</u> par</span>
                        <h6 class="">{{a.author|capfirst}}</h6>
                        Categorie : <a href="{% url 'theme' a.theme.slug %}">
                            {{a.theme}}
                        </a>
                    </div>
                </div>
            </div>


        </div>
            
        {% endfor %}
        <div class="card">
            {% include 'blog/pagination.html' %} 
        </div> 
    </div> 
    {% endif %}
</div>

{% endblock %}
{% block script %}
<script>
    $( document ).ready(function() {
        // if({{page_obj.number}} === 1){
        //    $('.menu-icon:button').click();
        // }
    }); 
</script>
{% endblock %}

templates/blog/pagination.html
{% load static %}
{% load paginator_tags %}
<nav aria-label="Pagination" pagination-mobile-items="true">
    <ul class="pagination text-center " >
    {% get_proper_elided_page_range paginator page_obj.number 1 1 as page_range %} 
    {% if page_obj.has_previous %}
        <!-- <li class=""><a href="?page=1">Première</a></li> -->
        <li class="pagination-previous "><a href="?page={{ page_obj.previous_page_number }}">Précédent</a></li>
    {% endif %}
    {% for page_num in page_range %}
        {% if page_obj.number == page_num %}
            <li class="current">
                <span class="show-for-sr" aria-label="Page-{{ page_num }}">{{ page_num }}</span>{{ page_obj.number }}
            </li>
        {% else %}
            {% if page_num == paginator.ELLIPSIS %}
                <li><span>{{ paginator.ELLIPSIS }}</span></li>
            {% else %}
                <li class="">
                    <a class="" aria-label="Page-{{ page_num }}" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
            {% endif %}
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}" aria-label="Page Suivante">Suivante</a></li>
        <!-- <li class=""><a href="?page={{ page_obj.paginator.num_pages }}">Dernière</a></li> -->
    {% endif %}
    </ul>
</div>